//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.02.05 at 03:52:32 PST
//


package hisglobal.transactionmgmnt.xmlTest.transaction;

/*
Developed By          : Partha P Chattaraj
Creation Dated        : 17-06-2006
Modification Dated    : 07-05-2008
Version               : HIMS 2.0

*/


/**
 * Java content class for transactionType complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="transactionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OPR" type="{http://www.example.org/transactionSchema}oprType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="MODULE_NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PROCESS_NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 */
public interface TransactionType {


    java.lang.String getPROCESSNAME();

    void setPROCESSNAME(java.lang.String value);

    java.lang.String getMODULENAME();

    void setMODULENAME(java.lang.String value);

    java.util.List getOPR();

}
