//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.02.05 at 03:52:32 PST
//


package hisglobal.transactionmgmnt.xmlTest.transaction;

/*
Developed By          : Partha P Chattaraj
Creation Dated        : 17-06-2006
Modification Dated    : 07-05-2008
Version               : HIMS 2.0

*/

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the transactionMgmnt.xmlTest.transaction package. <p>An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups.  Factory methods for each of these are provided in this class.
 *
 */
public class ObjectFactory
    extends com.sun.xml.bind.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap();

    static {
        defaultImplementations.put((hisglobal.transactionmgmnt.xmlTest.transaction.Transaction.class), (hisglobal.transactionmgmnt.xmlTest.transaction.impl.TransactionImpl.class));
        defaultImplementations.put((hisglobal.transactionmgmnt.xmlTest.transaction.BlockType.QRYType.class), (hisglobal.transactionmgmnt.xmlTest.transaction.impl.BlockTypeImpl.QRYTypeImpl.class));
        defaultImplementations.put((hisglobal.transactionmgmnt.xmlTest.transaction.OprType.class), (hisglobal.transactionmgmnt.xmlTest.transaction.impl.OprTypeImpl.class));
        defaultImplementations.put((hisglobal.transactionmgmnt.xmlTest.transaction.BlockType.class), (hisglobal.transactionmgmnt.xmlTest.transaction.impl.BlockTypeImpl.class));
        defaultImplementations.put((hisglobal.transactionmgmnt.xmlTest.transaction.TransactionType.class), (hisglobal.transactionmgmnt.xmlTest.transaction.impl.TransactionTypeImpl.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: transactionMgmnt.xmlTest.transaction
     *
     */
    public ObjectFactory() {
        super(new hisglobal.transactionmgmnt.xmlTest.transaction.ObjectFactory.GrammarInfoImpl());
    }

    /**
     * Create an instance of the specified Java content interface.
     *
     * @param javaContentInterface the Class object of the javacontent interface to instantiate
     * @return a new instance
     * @throws JAXBException if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     *
     * @param name the name of the property to retrieve
     * @return the value of the requested property
     * @throws PropertyException when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     *
     * @param name the name of the property to retrieve
     * @param value the value of the property to be set
     * @throws PropertyException when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of Transaction
     *
     * @throws JAXBException if an error occurs
     */
    public hisglobal.transactionmgmnt.xmlTest.transaction.Transaction createTransaction()
        throws javax.xml.bind.JAXBException
    {
        return ((hisglobal.transactionmgmnt.xmlTest.transaction.Transaction) newInstance((hisglobal.transactionmgmnt.xmlTest.transaction.Transaction.class)));
    }

    /**
     * Create an instance of BlockTypeQRYType
     *
     * @throws JAXBException if an error occurs
     */
    public hisglobal.transactionmgmnt.xmlTest.transaction.BlockType.QRYType createBlockTypeQRYType()
        throws javax.xml.bind.JAXBException
    {
        return ((hisglobal.transactionmgmnt.xmlTest.transaction.BlockType.QRYType) newInstance((hisglobal.transactionmgmnt.xmlTest.transaction.BlockType.QRYType.class)));
    }

    /**
     * Create an instance of OprType
     *
     * @throws JAXBException if an error occurs
     */
    public hisglobal.transactionmgmnt.xmlTest.transaction.OprType createOprType()
        throws javax.xml.bind.JAXBException
    {
        return ((hisglobal.transactionmgmnt.xmlTest.transaction.OprType) newInstance((hisglobal.transactionmgmnt.xmlTest.transaction.OprType.class)));
    }

    /**
     * Create an instance of BlockType
     *
     * @throws JAXBException if an error occurs
     */
    public hisglobal.transactionmgmnt.xmlTest.transaction.BlockType createBlockType()
        throws javax.xml.bind.JAXBException
    {
        return ((hisglobal.transactionmgmnt.xmlTest.transaction.BlockType) newInstance((hisglobal.transactionmgmnt.xmlTest.transaction.BlockType.class)));
    }

    /**
     * Create an instance of TransactionType
     *
     * @throws JAXBException if an error occurs
     */
    public hisglobal.transactionmgmnt.xmlTest.transaction.TransactionType createTransactionType()
        throws javax.xml.bind.JAXBException
    {
        return ((hisglobal.transactionmgmnt.xmlTest.transaction.TransactionType) newInstance((hisglobal.transactionmgmnt.xmlTest.transaction.TransactionType.class)));
    }

    private static class GrammarInfoImpl
        extends com.sun.xml.bind.GrammarInfo
    {


        public java.lang.Class getDefaultImplementation(java.lang.Class javaContentInterface) {
            return ((java.lang.Class) defaultImplementations.get(javaContentInterface));
        }

        public java.lang.Class getRootElement(java.lang.String uri, java.lang.String local) {
            if (("http://www.example.org/transactionSchema" == uri)&&("Transaction" == local)) {
                return (hisglobal.transactionmgmnt.xmlTest.transaction.impl.TransactionImpl.class);
            }
            return null;
        }

        public java.lang.String[] getProbePoints() {
            return new java.lang.String[] {"http://www.example.org/transactionSchema", "Transaction"};
        }

    }

}
