//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 11:55:54 AM GMT+05:30 
//


package bmed.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MmsConfigPhyStockVer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MmsConfigPhyStockVer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="strToleranceLimit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MmsConfigPhyStockVer", propOrder = {
    "strToleranceLimit"
})
public class EmmsConfigPhyStockVer {

    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String strToleranceLimit;

    /**
     * Gets the value of the strToleranceLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrToleranceLimit() {
        return strToleranceLimit;
    }

    /**
     * Sets the value of the strToleranceLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrToleranceLimit(String value) {
        this.strToleranceLimit = value;
    }

}
