//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 11:55:54 AM GMT+05:30 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cdacnoida.in/his/EmmsConfig")
package bmed.setup;
