//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.23 at 07:40:31 AM IST 
//


package billing.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillFormatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillFormatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="header2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="header3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="header4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="footer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disclaimerWithoutCrNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disclaimerServices" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disclaimerRefund" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disclaimerAdvance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disclaimerPartPayment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disclaimerFinalBill" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="duplicatePrintReq" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billLineOpdServices" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillFormatType", propOrder = {
    "header1",
    "header2",
    "header3",
    "header4",
    "footer",
    "disclaimerWithoutCrNo",
    "disclaimerServices",
    "disclaimerRefund",
    "disclaimerAdvance",
    "disclaimerPartPayment",
    "disclaimerFinalBill",
    "duplicatePrintReq",
    "billLineOpdServices"
})
public class BillFormatType {

    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String header1;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String header2;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String header3;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String header4;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String footer;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String disclaimerWithoutCrNo;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String disclaimerServices;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String disclaimerRefund;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String disclaimerAdvance;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String disclaimerPartPayment;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String disclaimerFinalBill;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String duplicatePrintReq;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String billLineOpdServices;

    /**
     * Gets the value of the header1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeader1() {
        return header1;
    }

    /**
     * Sets the value of the header1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeader1(String value) {
        this.header1 = value;
    }

    /**
     * Gets the value of the header2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeader2() {
        return header2;
    }

    /**
     * Sets the value of the header2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeader2(String value) {
        this.header2 = value;
    }

    /**
     * Gets the value of the header3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeader3() {
        return header3;
    }

    /**
     * Sets the value of the header3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeader3(String value) {
        this.header3 = value;
    }

    /**
     * Gets the value of the header4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeader4() {
        return header4;
    }

    /**
     * Sets the value of the header4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeader4(String value) {
        this.header4 = value;
    }

    /**
     * Gets the value of the footer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFooter() {
        return footer;
    }

    /**
     * Sets the value of the footer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFooter(String value) {
        this.footer = value;
    }

    /**
     * Gets the value of the disclaimerWithoutCrNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimerWithoutCrNo() {
        return disclaimerWithoutCrNo;
    }

    /**
     * Sets the value of the disclaimerWithoutCrNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimerWithoutCrNo(String value) {
        this.disclaimerWithoutCrNo = value;
    }

    /**
     * Gets the value of the disclaimerServices property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimerServices() {
        return disclaimerServices;
    }

    /**
     * Sets the value of the disclaimerServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimerServices(String value) {
        this.disclaimerServices = value;
    }

    /**
     * Gets the value of the disclaimerRefund property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimerRefund() {
        return disclaimerRefund;
    }

    /**
     * Sets the value of the disclaimerRefund property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimerRefund(String value) {
        this.disclaimerRefund = value;
    }

    /**
     * Gets the value of the disclaimerAdvance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimerAdvance() {
        return disclaimerAdvance;
    }

    /**
     * Sets the value of the disclaimerAdvance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimerAdvance(String value) {
        this.disclaimerAdvance = value;
    }

    /**
     * Gets the value of the disclaimerPartPayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimerPartPayment() {
        return disclaimerPartPayment;
    }

    /**
     * Sets the value of the disclaimerPartPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimerPartPayment(String value) {
        this.disclaimerPartPayment = value;
    }

    /**
     * Gets the value of the disclaimerFinalBill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimerFinalBill() {
        return disclaimerFinalBill;
    }

    /**
     * Sets the value of the disclaimerFinalBill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimerFinalBill(String value) {
        this.disclaimerFinalBill = value;
    }

    /**
     * Gets the value of the duplicatePrintReq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuplicatePrintReq() {
        return duplicatePrintReq;
    }

    /**
     * Sets the value of the duplicatePrintReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuplicatePrintReq(String value) {
        this.duplicatePrintReq = value;
    }

    /**
     * Gets the value of the billLineOpdServices property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillLineOpdServices() {
        return billLineOpdServices;
    }

    /**
     * Sets the value of the billLineOpdServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillLineOpdServices(String value) {
        this.billLineOpdServices = value;
    }

}
