//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.23 at 07:40:31 AM IST 
//


package billing.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeneralType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneralType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cancellationTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="duplicatePrintCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="recordsDisplayMaster" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="levelModifyMaster" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="levelDeleteMaster" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="receiptType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="duplicatePrint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isWithoutCrNoRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="onlineRefundRequestAllowed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isReferringPhysicianRequiredInt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isReferringPhysicianRequiredExt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isPreviousCrNoRequiredInt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isPreviousCrNoRequiredExt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ccConfermationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isPrevCrNoSearchingReqInt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isPrevCrNoSearchingReqExt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="chargeTypeExt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wardTypeExt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="chargeTypeInt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wardTypeInt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dayEndBillingProcessType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dayEndBillingDateType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dayEndNonBillingProcessType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dayEndNonBillingDateType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="opdReceiptType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipdReceiptType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ccRefundRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="printMessageLimit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="refundReceiptType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="refundAgainstRefundRequest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="internalPatient" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="externalPatient" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isApprovalByRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralType", propOrder = {
    "cancellationTime",
    "duplicatePrintCharge",
    "recordsDisplayMaster",
    "levelModifyMaster",
    "levelDeleteMaster",
    "receiptType",
    "duplicatePrint",
    "isWithoutCrNoRequired",
    "onlineRefundRequestAllowed",
    "isReferringPhysicianRequiredInt",
    "isReferringPhysicianRequiredExt",
    "isPreviousCrNoRequiredInt",
    "isPreviousCrNoRequiredExt",
    "ccConfermationType",
    "isPrevCrNoSearchingReqInt",
    "isPrevCrNoSearchingReqExt",
    "chargeTypeExt",
    "wardTypeExt",
    "chargeTypeInt",
    "wardTypeInt",
    "dayEndBillingProcessType",
    "dayEndBillingDateType",
    "dayEndNonBillingProcessType",
    "dayEndNonBillingDateType",
    "opdReceiptType",
    "ipdReceiptType",
    "ccRefundRequired",
    "printMessageLimit",
    "refundReceiptType",
    "refundAgainstRefundRequest",
    "internalPatient",
    "externalPatient",
    "isApprovalByRequired"
})
public class GeneralType {

    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String cancellationTime;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String duplicatePrintCharge;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String recordsDisplayMaster;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String levelModifyMaster;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String levelDeleteMaster;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String receiptType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String duplicatePrint;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String isWithoutCrNoRequired;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String onlineRefundRequestAllowed;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String isReferringPhysicianRequiredInt;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String isReferringPhysicianRequiredExt;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String isPreviousCrNoRequiredInt;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String isPreviousCrNoRequiredExt;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String ccConfermationType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String isPrevCrNoSearchingReqInt;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String isPrevCrNoSearchingReqExt;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String chargeTypeExt;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String wardTypeExt;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String chargeTypeInt;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String wardTypeInt;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String dayEndBillingProcessType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String dayEndBillingDateType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String dayEndNonBillingProcessType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String dayEndNonBillingDateType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String opdReceiptType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String ipdReceiptType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String ccRefundRequired;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String printMessageLimit;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String refundReceiptType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String refundAgainstRefundRequest;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String internalPatient;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String externalPatient;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String isApprovalByRequired;

    /**
     * Gets the value of the cancellationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellationTime() {
        return cancellationTime;
    }

    /**
     * Sets the value of the cancellationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationTime(String value) {
        this.cancellationTime = value;
    }

    /**
     * Gets the value of the duplicatePrintCharge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuplicatePrintCharge() {
        return duplicatePrintCharge;
    }

    /**
     * Sets the value of the duplicatePrintCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuplicatePrintCharge(String value) {
        this.duplicatePrintCharge = value;
    }

    /**
     * Gets the value of the recordsDisplayMaster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordsDisplayMaster() {
        return recordsDisplayMaster;
    }

    /**
     * Sets the value of the recordsDisplayMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordsDisplayMaster(String value) {
        this.recordsDisplayMaster = value;
    }

    /**
     * Gets the value of the levelModifyMaster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelModifyMaster() {
        return levelModifyMaster;
    }

    /**
     * Sets the value of the levelModifyMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelModifyMaster(String value) {
        this.levelModifyMaster = value;
    }

    /**
     * Gets the value of the levelDeleteMaster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelDeleteMaster() {
        return levelDeleteMaster;
    }

    /**
     * Sets the value of the levelDeleteMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelDeleteMaster(String value) {
        this.levelDeleteMaster = value;
    }

    /**
     * Gets the value of the receiptType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptType() {
        return receiptType;
    }

    /**
     * Sets the value of the receiptType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptType(String value) {
        this.receiptType = value;
    }

    /**
     * Gets the value of the duplicatePrint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuplicatePrint() {
        return duplicatePrint;
    }

    /**
     * Sets the value of the duplicatePrint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuplicatePrint(String value) {
        this.duplicatePrint = value;
    }

    /**
     * Gets the value of the isWithoutCrNoRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsWithoutCrNoRequired() {
        return isWithoutCrNoRequired;
    }

    /**
     * Sets the value of the isWithoutCrNoRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsWithoutCrNoRequired(String value) {
        this.isWithoutCrNoRequired = value;
    }

    /**
     * Gets the value of the onlineRefundRequestAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnlineRefundRequestAllowed() {
        return onlineRefundRequestAllowed;
    }

    /**
     * Sets the value of the onlineRefundRequestAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnlineRefundRequestAllowed(String value) {
        this.onlineRefundRequestAllowed = value;
    }

    /**
     * Gets the value of the isReferringPhysicianRequiredInt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsReferringPhysicianRequiredInt() {
        return isReferringPhysicianRequiredInt;
    }

    /**
     * Sets the value of the isReferringPhysicianRequiredInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsReferringPhysicianRequiredInt(String value) {
        this.isReferringPhysicianRequiredInt = value;
    }

    /**
     * Gets the value of the isReferringPhysicianRequiredExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsReferringPhysicianRequiredExt() {
        return isReferringPhysicianRequiredExt;
    }

    /**
     * Sets the value of the isReferringPhysicianRequiredExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsReferringPhysicianRequiredExt(String value) {
        this.isReferringPhysicianRequiredExt = value;
    }

    /**
     * Gets the value of the isPreviousCrNoRequiredInt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPreviousCrNoRequiredInt() {
        return isPreviousCrNoRequiredInt;
    }

    /**
     * Sets the value of the isPreviousCrNoRequiredInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPreviousCrNoRequiredInt(String value) {
        this.isPreviousCrNoRequiredInt = value;
    }

    /**
     * Gets the value of the isPreviousCrNoRequiredExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPreviousCrNoRequiredExt() {
        return isPreviousCrNoRequiredExt;
    }

    /**
     * Sets the value of the isPreviousCrNoRequiredExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPreviousCrNoRequiredExt(String value) {
        this.isPreviousCrNoRequiredExt = value;
    }

    /**
     * Gets the value of the ccConfermationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcConfermationType() {
        return ccConfermationType;
    }

    /**
     * Sets the value of the ccConfermationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcConfermationType(String value) {
        this.ccConfermationType = value;
    }

    /**
     * Gets the value of the isPrevCrNoSearchingReqInt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPrevCrNoSearchingReqInt() {
        return isPrevCrNoSearchingReqInt;
    }

    /**
     * Sets the value of the isPrevCrNoSearchingReqInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPrevCrNoSearchingReqInt(String value) {
        this.isPrevCrNoSearchingReqInt = value;
    }

    /**
     * Gets the value of the isPrevCrNoSearchingReqExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPrevCrNoSearchingReqExt() {
        return isPrevCrNoSearchingReqExt;
    }

    /**
     * Sets the value of the isPrevCrNoSearchingReqExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPrevCrNoSearchingReqExt(String value) {
        this.isPrevCrNoSearchingReqExt = value;
    }

    /**
     * Gets the value of the chargeTypeExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeTypeExt() {
        return chargeTypeExt;
    }

    /**
     * Sets the value of the chargeTypeExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeTypeExt(String value) {
        this.chargeTypeExt = value;
    }

    /**
     * Gets the value of the wardTypeExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWardTypeExt() {
        return wardTypeExt;
    }

    /**
     * Sets the value of the wardTypeExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWardTypeExt(String value) {
        this.wardTypeExt = value;
    }

    /**
     * Gets the value of the chargeTypeInt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeTypeInt() {
        return chargeTypeInt;
    }

    /**
     * Sets the value of the chargeTypeInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeTypeInt(String value) {
        this.chargeTypeInt = value;
    }

    /**
     * Gets the value of the wardTypeInt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWardTypeInt() {
        return wardTypeInt;
    }

    /**
     * Sets the value of the wardTypeInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWardTypeInt(String value) {
        this.wardTypeInt = value;
    }

    /**
     * Gets the value of the dayEndBillingProcessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayEndBillingProcessType() {
        return dayEndBillingProcessType;
    }

    /**
     * Sets the value of the dayEndBillingProcessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayEndBillingProcessType(String value) {
        this.dayEndBillingProcessType = value;
    }

    /**
     * Gets the value of the dayEndBillingDateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayEndBillingDateType() {
        return dayEndBillingDateType;
    }

    /**
     * Sets the value of the dayEndBillingDateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayEndBillingDateType(String value) {
        this.dayEndBillingDateType = value;
    }

    /**
     * Gets the value of the dayEndNonBillingProcessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayEndNonBillingProcessType() {
        return dayEndNonBillingProcessType;
    }

    /**
     * Sets the value of the dayEndNonBillingProcessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayEndNonBillingProcessType(String value) {
        this.dayEndNonBillingProcessType = value;
    }

    /**
     * Gets the value of the dayEndNonBillingDateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayEndNonBillingDateType() {
        return dayEndNonBillingDateType;
    }

    /**
     * Sets the value of the dayEndNonBillingDateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayEndNonBillingDateType(String value) {
        this.dayEndNonBillingDateType = value;
    }

    /**
     * Gets the value of the opdReceiptType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpdReceiptType() {
        return opdReceiptType;
    }

    /**
     * Sets the value of the opdReceiptType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpdReceiptType(String value) {
        this.opdReceiptType = value;
    }

    /**
     * Gets the value of the ipdReceiptType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpdReceiptType() {
        return ipdReceiptType;
    }

    /**
     * Sets the value of the ipdReceiptType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpdReceiptType(String value) {
        this.ipdReceiptType = value;
    }

    /**
     * Gets the value of the ccRefundRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcRefundRequired() {
        return ccRefundRequired;
    }

    /**
     * Sets the value of the ccRefundRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcRefundRequired(String value) {
        this.ccRefundRequired = value;
    }

    /**
     * Gets the value of the printMessageLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintMessageLimit() {
        return printMessageLimit;
    }

    /**
     * Sets the value of the printMessageLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintMessageLimit(String value) {
        this.printMessageLimit = value;
    }

    /**
     * Gets the value of the refundReceiptType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundReceiptType() {
        return refundReceiptType;
    }

    /**
     * Sets the value of the refundReceiptType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundReceiptType(String value) {
        this.refundReceiptType = value;
    }

    /**
     * Gets the value of the refundAgainstRefundRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundAgainstRefundRequest() {
        return refundAgainstRefundRequest;
    }

    /**
     * Sets the value of the refundAgainstRefundRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundAgainstRefundRequest(String value) {
        this.refundAgainstRefundRequest = value;
    }

    /**
     * Gets the value of the internalPatient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalPatient() {
        return internalPatient;
    }

    /**
     * Sets the value of the internalPatient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalPatient(String value) {
        this.internalPatient = value;
    }

    /**
     * Gets the value of the externalPatient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalPatient() {
        return externalPatient;
    }

    /**
     * Sets the value of the externalPatient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalPatient(String value) {
        this.externalPatient = value;
    }

	public String getIsApprovalByRequired() {
		return isApprovalByRequired;
	}

	public void setIsApprovalByRequired(String isApprovalByRequired) {
		this.isApprovalByRequired = isApprovalByRequired;
	}

}
