//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.23 at 07:40:31 AM IST 
//


package billing.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IpdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IpdType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="thirdParyBilling" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="discountClerk" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="refundPenalty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creditBilling" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="partPaymentDuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="roundOff" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceTaxOnTotalBill" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="excessCreditLimit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipdGenAdtProcessType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipdServiceTax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipdFreeCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IpdType", propOrder = {
    "thirdParyBilling",
    "discount",
    "discountClerk",
    "refundPenalty",
    "creditBilling",
    "partPaymentDuration",
    "roundOff",
    "serviceTaxOnTotalBill",
    "excessCreditLimit",
    "ipdGenAdtProcessType",
    "ipdServiceTax",
    "ipdFreeCategory"
})
public class IpdType {

    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String thirdParyBilling;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String discount;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String discountClerk;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String refundPenalty;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String creditBilling;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String partPaymentDuration;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String roundOff;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String serviceTaxOnTotalBill;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String excessCreditLimit;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String ipdGenAdtProcessType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String ipdServiceTax;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String ipdFreeCategory;

    /**
     * Gets the value of the thirdParyBilling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdParyBilling() {
        return thirdParyBilling;
    }

    /**
     * Sets the value of the thirdParyBilling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdParyBilling(String value) {
        this.thirdParyBilling = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscount(String value) {
        this.discount = value;
    }

    /**
     * Gets the value of the discountClerk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountClerk() {
        return discountClerk;
    }

    /**
     * Sets the value of the discountClerk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountClerk(String value) {
        this.discountClerk = value;
    }

    /**
     * Gets the value of the refundPenalty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundPenalty() {
        return refundPenalty;
    }

    /**
     * Sets the value of the refundPenalty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundPenalty(String value) {
        this.refundPenalty = value;
    }

    /**
     * Gets the value of the creditBilling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditBilling() {
        return creditBilling;
    }

    /**
     * Sets the value of the creditBilling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditBilling(String value) {
        this.creditBilling = value;
    }

    /**
     * Gets the value of the partPaymentDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartPaymentDuration() {
        return partPaymentDuration;
    }

    /**
     * Sets the value of the partPaymentDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartPaymentDuration(String value) {
        this.partPaymentDuration = value;
    }

    /**
     * Gets the value of the roundOff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoundOff() {
        return roundOff;
    }

    /**
     * Sets the value of the roundOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoundOff(String value) {
        this.roundOff = value;
    }

    /**
     * Gets the value of the serviceTaxOnTotalBill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceTaxOnTotalBill() {
        return serviceTaxOnTotalBill;
    }

    /**
     * Sets the value of the serviceTaxOnTotalBill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceTaxOnTotalBill(String value) {
        this.serviceTaxOnTotalBill = value;
    }

    /**
     * Gets the value of the excessCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcessCreditLimit() {
        return excessCreditLimit;
    }

    /**
     * Sets the value of the excessCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcessCreditLimit(String value) {
        this.excessCreditLimit = value;
    }

    /**
     * Gets the value of the ipdGenAdtProcessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpdGenAdtProcessType() {
        return ipdGenAdtProcessType;
    }

    /**
     * Sets the value of the ipdGenAdtProcessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpdGenAdtProcessType(String value) {
        this.ipdGenAdtProcessType = value;
    }

    /**
     * Gets the value of the ipdServiceTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpdServiceTax() {
        return ipdServiceTax;
    }

    /**
     * Sets the value of the ipdServiceTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpdServiceTax(String value) {
        this.ipdServiceTax = value;
    }

    /**
     * Gets the value of the ipdFreeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpdFreeCategory() {
        return ipdFreeCategory;
    }

    /**
     * Sets the value of the ipdFreeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpdFreeCategory(String value) {
        this.ipdFreeCategory = value;
    }

}
