//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.23 at 07:40:31 AM IST 
//


package billing.setup;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the billing.setup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Setup_QNAME = new QName("http://www.cdacnoida.in/his/setup_bill", "setup");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: billing.setup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetupType }
     * 
     */
    public SetupType createSetupType() {
        return new SetupType();
    }

    /**
     * Create an instance of {@link GeneralType }
     * 
     */
    public GeneralType createGeneralType() {
        return new GeneralType();
    }

    /**
     * Create an instance of {@link BillFormatType }
     * 
     */
    public BillFormatType createBillFormatType() {
        return new BillFormatType();
    }

    /**
     * Create an instance of {@link IpdType }
     * 
     */
    public IpdType createIpdType() {
        return new IpdType();
    }

    /**
     * Create an instance of {@link OpdType }
     * 
     */
    public OpdType createOpdType() {
        return new OpdType();
    }

    /**
     * Create an instance of {@link EmergencyType }
     * 
     */
    public EmergencyType createEmergencyType() {
        return new EmergencyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetupType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cdacnoida.in/his/setup_bill", name = "setup")
    public JAXBElement<SetupType> createSetup(SetupType value) {
        return new JAXBElement<SetupType>(_Setup_QNAME, SetupType.class, null, value);
    }

}
