//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.23 at 07:40:31 AM IST 
//


package billing.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpdType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="thirdParyBilling" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="discountClerk" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="refundPenalty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="roundOff" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="opdServiceTax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="opdFreeCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpdType", propOrder = {
    "thirdParyBilling",
    "discount",
    "discountClerk",
    "refundPenalty",
    "roundOff",
    "opdServiceTax",
    "opdFreeCategory"
})
public class OpdType {

    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String thirdParyBilling;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String discount;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String discountClerk;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String refundPenalty;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String roundOff;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String opdServiceTax;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/setup_bill", required = true)
    protected String opdFreeCategory;

    /**
     * Gets the value of the thirdParyBilling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdParyBilling() {
        return thirdParyBilling;
    }

    /**
     * Sets the value of the thirdParyBilling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdParyBilling(String value) {
        this.thirdParyBilling = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscount(String value) {
        this.discount = value;
    }

    /**
     * Gets the value of the discountClerk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountClerk() {
        return discountClerk;
    }

    /**
     * Sets the value of the discountClerk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountClerk(String value) {
        this.discountClerk = value;
    }

    /**
     * Gets the value of the refundPenalty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundPenalty() {
        return refundPenalty;
    }

    /**
     * Sets the value of the refundPenalty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundPenalty(String value) {
        this.refundPenalty = value;
    }

    /**
     * Gets the value of the roundOff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoundOff() {
        return roundOff;
    }

    /**
     * Sets the value of the roundOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoundOff(String value) {
        this.roundOff = value;
    }

    /**
     * Gets the value of the opdServiceTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpdServiceTax() {
        return opdServiceTax;
    }

    /**
     * Sets the value of the opdServiceTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpdServiceTax(String value) {
        this.opdServiceTax = value;
    }

    /**
     * Gets the value of the opdFreeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpdFreeCategory() {
        return opdFreeCategory;
    }

    /**
     * Sets the value of the opdFreeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpdFreeCategory(String value) {
        this.opdFreeCategory = value;
    }

}
