//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.23 at 07:40:31 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cdacnoida.in/his/setup_bill")
package billing.setup;
