//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.18 at 04:08:17 PM IST 
//


package hisglobal.exceptions;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hisglobal.error package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HisError_QNAME = new QName("http://www.example.org/ErrorId", "hisError");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hisglobal.error
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HisErrorType }
     * 
     */
    public HisErrorType createHisErrorType() {
        return new HisErrorType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HisErrorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/ErrorId", name = "hisError")
    public JAXBElement<HisErrorType> createHisError(HisErrorType value) {
        return new JAXBElement<HisErrorType>(_HisError_QNAME, HisErrorType.class, null, value);
    }

}
