package hisglobal.utility.generictemplate;

import hisglobal.hisconfig.Config;

/**
 * @copyright CDAC
 * @developer Pragya Sharma
 */

public interface GenericTemplateConfig
{
	// Template Types
	String[] TEMPLATE_TYPES = {"", "Normal" , "Matrix", "Consent", "Guideline"};
	String TEMPLATE_TYPE_NORMAL = Integer.toString(TemplateDesignerUtility.TEMPLATE_TYPE_NORMAL);
	String TEMPLATE_TYPE_MATRIX = Integer.toString(TemplateDesignerUtility.TEMPLATE_TYPE_MATRIX);
	String TEMPLATE_TYPE_CONSENT = Integer.toString(TemplateDesignerUtility.TEMPLATE_TYPE_CONSENT);
	String TEMPLATE_TYPE_GUIDELINE = Integer.toString(TemplateDesignerUtility.TEMPLATE_TYPE_GUIDELINE);

	// Parameter Starts With
	String PARAMETER_STARTS_WITH="PARAMETER@";
	
	// Query Files 
	String QUERY_FILE_FOR_GENERIC_TEMPLATE = "hisglobal.utility.generictemplate.genericTemplateQuery";

	// Session Attributes Keys
	String ESSENTIAL_LIST_ALL_TEMPLATE_GROUP = "essentialListAllTemplateGroup";
	String ESSENTIAL_LIST_ALL_TEMPLATE_CATEGORY = "essentialListAllTemplateCategory";
	String ESSENTIAL_LIST_ALL_CLINICAL_PARAMETERS = "essentialListAllClinicalParameters";
	String ESSENTIAL_LIST_ALL_INFORMATION_CONTROL_VALUES = "essentialListAllInformationControlValues"; 
	String GENERIC_TEMPLATE_PARAMETER_VALUES_MAP_TEMPLATE_MAP = "genericTemplateParameterValuesMapOfTempMap";
	String GENERIC_TEMPLATE_PARAMETER_VALUES_DETAIL_MAP = "genericTemplateParameterValuesDetailMap";
	String GENERIC_TEMPLATE_DETAIL_VO = "genericTemplateDetailVO";

    String CHOICE_MISTAKE ="1";
    String CHOICE_ADDITION ="2";
    
    String YES = "1";
    String NO = "0";
    
    // Information Bean
    String GENERIC_TEMPLATE_INFORMATION_BEAN = "genericTemplateInformationBean";
    // Gender Codes
	String GENDER_CODE_MALE = Config.GENDER_TYPE_MALE;
	String GENDER_CODE_FEMALE = Config.GENDER_TYPE_FEMALE;
	String GENDER_CODE_OTHER = Config.GENDER_TYPE_OTHER;
	
	// Parameter Bound
	String PARAMETER_BOUND_NON_PATIENT_CENTRIC = "1";
	String PARAMETER_BOUND_PATIENT_CENTRIC = "2";

	// Template Group
	String TEMPLATE_GROUP_CLINICAL = "11";
	String TEMPLATE_GROUP_DESCRIPTIVE = "12";
	String TEMPLATE_GROUP_NON_CLINICAL = "13";
	String TEMPLATE_GROUP_OT = "14";
	String TEMPLATE_GROUP_QUALITY = "15";
	String TEMPLATE_GROUP_SERVICE_AREA = "16";

	
	// Parameter Type
	String PARAMETER_TYPE_COMPLAINT = "11";
	String PARAMETER_TYPE_HISTORY = "12";
	String PARAMETER_TYPE_EXAMINATION = "13";
	String PARAMETER_TYPE_CLINICAL_NOTES = "14";	// OT Templates
	String PARAMETER_TYPE_PRESENT_PATIENT_ALERTS = "15";
	String PARAMETER_TYPE_CONSENT = "16";
	String PARAMETER_TYPE_GUIDELINES = "17";
	String PARAMETER_TYPE_VITAL_MONITORING = "18";
	String PARAMETER_TYPE_MEDICAL_CERTIFICATE = "19";
	String PARAMETER_TYPE_FITNESS_CERTIFICATE = "20";
	String PARAMETER_TYPE_BLOOD_DONATION_CONFIRMATION = "21";
	String PARAMETER_TYPE_VOLUNTARY_CARD = "22";
	String PARAMETER_TYPE_APHERESIS_MACHINE_TEMPLATE = "23";
	String PARAMETER_TYPE_BLOOD_BANK_QUALITY = "24";
	String PARAMETER_TYPE_DRUG_REACTION = "25";
	String PARAMETER_TYPE_TRANSFUSSION_REACTION = "26";
	String PARAMETER_TYPE_DONOR_ADVERSE_REACTION = "27";
	String PARAMETER_TYPE_POSTMORTEM = "28";
	String PARAMETER_TYPE_SERVICE_AREA = "29";
	String PARAMETER_TYPE_DIET_KITCHEN_QUALITY = "30";
	String PARAMETER_TYPE_MEDICAL_BOARD="31";
	String PARAMETER_TYPE_DIET_KITCHEN_MEDICAL_CHECKUP = "32";
	String PARAMETER_TYPE_BIO_MEDICAL_WASTE="33";
	
	// Template Category
	String TEMPLATE_CATEGORY_COMPLAINT = PARAMETER_TYPE_COMPLAINT;
	String TEMPLATE_CATEGORY_HISTORY = PARAMETER_TYPE_HISTORY;
	String TEMPLATE_CATEGORY_EXAMINATION = PARAMETER_TYPE_EXAMINATION;
	String TEMPLATE_CATEGORY_CLINICAL_NOTES = PARAMETER_TYPE_CLINICAL_NOTES;	// OT Templates
	String TEMPLATE_CATEGORY_PRESENT_PATIENT_ALERTS = PARAMETER_TYPE_PRESENT_PATIENT_ALERTS;
	String TEMPLATE_CATEGORY_CONSENT = PARAMETER_TYPE_CONSENT;
	String TEMPLATE_CATEGORY_GUIDELINES = PARAMETER_TYPE_GUIDELINES;
	String TEMPLATE_CATEGORY_VITAL_MONITORING = PARAMETER_TYPE_VITAL_MONITORING;
	String TEMPLATE_CATEGORY_MEDICAL_CERTIFICATE = PARAMETER_TYPE_MEDICAL_CERTIFICATE;
	String TEMPLATE_CATEGORY_FITNESS_CERTIFICATE = PARAMETER_TYPE_FITNESS_CERTIFICATE;
	String TEMPLATE_CATEGORY_BLOOD_DONATION_CONFIRMATION = PARAMETER_TYPE_BLOOD_DONATION_CONFIRMATION;
	String TEMPLATE_CATEGORY_VOLUNTARY_CARD = PARAMETER_TYPE_VOLUNTARY_CARD;
	String TEMPLATE_CATEGORY_APHERESIS_MACHINE_TEMPLATE = PARAMETER_TYPE_APHERESIS_MACHINE_TEMPLATE;
	String TEMPLATE_CATEGORY_PARAMETER_TYPE_BLOOD_BANK_QUALITY = PARAMETER_TYPE_BLOOD_BANK_QUALITY;
	String TEMPLATE_CATEGORY_DRUG_REACTION = PARAMETER_TYPE_DRUG_REACTION;
	String TEMPLATE_CATEGORY_TRANSFUSSION_REACTION = PARAMETER_TYPE_TRANSFUSSION_REACTION;
	String TEMPLATE_CATEGORY_DONOR_ADVERSE_REACTION = PARAMETER_TYPE_DONOR_ADVERSE_REACTION;
	String TEMPLATE_CATEGORY_POSTMORTEM = PARAMETER_TYPE_POSTMORTEM;
	String TEMPLATE_CATEGORY_SERVICE_AREA = PARAMETER_TYPE_SERVICE_AREA;	
	String TEMPLATE_CATEGORY_DIET_KITCHEN_QUALITY = PARAMETER_TYPE_DIET_KITCHEN_QUALITY;	
	String TEMPLATE_CATEGORY_MEDICAL_BOARD = PARAMETER_TYPE_MEDICAL_BOARD;
	String TEMPLATE_CATEGORY_DIET_KITCHEN_MEDICAL_CHECKUP = PARAMETER_TYPE_DIET_KITCHEN_MEDICAL_CHECKUP;
	String TEMPLATE_CATEGORY_BIO_MEDICAL_WASTE = PARAMETER_TYPE_BIO_MEDICAL_WASTE;

	// Parameter Range
	String GENERIC_TEMPLATE_PATIENT_GENDER_TYPE = "genericTemplatePatientGenderType";
	String GENERIC_TEMPLATE_PATIENT_INITIAL_GENDER_TYPE = TemplateDesignerUtility.GENDER_TYPES_NONE; //Config.GENDER_TYPE_MALE;
	String GENERIC_TEMPLATE_PATIENT_AGE = "genericTemplatePatientAge";
    
	String GET_PARAMETER_RANGE_PROC = "PKG_MRD_DTL.GET_PARAMETER_RANGE_BY_PARAID";
	
	// Template Display modes
	String GENERIC_TEMPLATE_MODE_EDITABLE = "1";
	String GENERIC_TEMPLATE_MODE_REPORT = "2";
	String GENERIC_TEMPLATE_MODE_SUMMARIZED_REPORT = "3";
	String GENERIC_TEMPLATE_MODE_EDITABLE_NON_ENTERED = "4";
	String GENERIC_TEMPLATE_MODE_EDITABLE_FOCUS_ENTERED = "5";
	String GENERIC_TEMPLATE_MODE_SHORT_SUMMARIZED_REPORT = "6";
	
	// Generic Chart Display modes
	String GENERIC_CHART_MODE_TABLE_TEMP_WISE = "1";
	String GENERIC_CHART_MODE_TABLE_PARA_WISE = "2";

	
	// Template Desk Tile Specific
		// List of Template Unit, Ward, Seat, Desk, Desk Menu Wise
	String PROC_FOR_TEMPLATE_LIST = "PKG_MRD_DTL.GET_GENERIC_TEMPLATES_LIST";
	String TEMPLATE_TILE_ALL_TEMPLATE_LIST = "templateTileAllTemplateList";
	String TEMPLATE_TILE_DEFAULT_TEMPLATE_LIST = "templateTileDefaultTemplateList";
	String TEMPLATE_TILE_DEFAULT_TEMPLATE_LIST_COMPLAINT = "templateTileDefaultTemplateListComplaint";
	String TEMPLATE_TILE_DEFAULT_TEMPLATE_LIST_HISTORY = "templateTileDefaultTemplateListHistory";
	String TEMPLATE_TILE_DEFAULT_TEMPLATE_LIST_EXAMINATION = "templateTileDefaultTemplateListExamination";
	String TEMPLATE_TILE_UNDEFAULT_TEMPLATE_LIST = "templateTileUndefaultTemplateList";
		// Template Report
	String TEMPLATE_VIEW_REPORT_TYPE_MODE_TEMPLATE_WISE = "TemplateWise";
	String TEMPLATE_VIEW_REPORT_TYPE_MODE_PARAMETER_WISE = "ParameterWise";
		
	
	// Chart View Modes
	String GENERIC_CHART_VIEW_MODE_TEMP_WISE_TABLE = "TempWiseTable";
	String GENERIC_CHART_VIEW_MODE_PARA_WISE_LIST = "ParaWiseTable";
	String GENERIC_CHART_VIEW_MODE_PARA_WISE_CHART_TABLE = "ParaWiseChartTable";
	
	// Template Charting
	String TEMPLATE_CHART_TEMPLATE_LIST_MAP = "templateChartTemplateListMap";
	String TEMPLATE_CHART_TEMPLATE_PARAMETER_LIST_MAP = "templateChartTemplateParameterListMap";
	String TEMPLATE_CHART_DATA_DATES_LIST_MAP = "templateChartDataDatesListMap";
	String TEMPLATE_CHART_DATES_PARA_VALUE_MAP = "templateChartDatesDataValueMap";
	
	String PARAMETER_TYPE_LIST="parameterType";

	String GENERIC_CHART_VIEW_MODE = "genericChartViewMode";
	String GENERIC_CHART_TEMPLATE_LIST_MAP = "genericChartTemplateListMap";
	String GENERIC_CHART_TEMPLATE_PARAMETER_LIST_MAP = "genericChartTemplateParameterListMap";
	String GENERIC_CHART_PARAMETER_LIST = "genericChartParameterList";
	String GENERIC_CHART_DATA_DATES_LIST_MAP = "genericChartDataDatesListMap";
	String GENERIC_CHART_DATES_PARA_VALUE_MAP = "genericChartDatesDataValueMap";
	String GENERIC_CHART_DATES_PARA_DETAIL_MAP = "genericChartDatesParaDetailMap";

	// HTML Parsing & PDF Conversion Images 
	String imgCheckBoxPath="\\hisglobal\\utility\\generictemplate\\images\\checkbox.png";
	String imgRadioPath="\\hisglobal\\utility\\generictemplate\\images\\radio.png";
	String imgCheckBoxCheckedPath="\\hisglobal\\utility\\generictemplate\\images\\checkboxSelected.png";
	String imgRadioCheckedPath="\\hisglobal\\utility\\generictemplate\\images\\radioSelected.png";
	
	// Template Category Wise Mapping Specific
	String PROC_FOR_CATEGORY_WISE_TEMPLATE_LIST = "GET_CATEGORY_WISE_TEMPLATES"; // Not in Use , Dropped
	
	// Template ImageView Control Related
	String GENERIC_TEMPLATE_IMAGEVIEW_UPLOADED_IMAGE_FILE_DATA_MAP = "genericTemplateImageViewUploadedImageFileDataMap";
}
