//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.08 at 12:34:03 PM IST 
//


package mms.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MmsConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MmsConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mmsIssueProcess" type="{http://www.cdacnoida.in/his/MmsConfig}MmsIssueProcessType"/>
 *         &lt;element name="mmsConfigGerneral" type="{http://www.cdacnoida.in/his/MmsConfig}MmsConfigGeneral"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MmsConfigType", propOrder = {
    "mmsIssueProcess",
    "mmsConfigGerneral"
})
public class MmsConfigType {

    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected MmsIssueProcessType mmsIssueProcess;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected MmsConfigGeneral mmsConfigGerneral;

    /**
     * Gets the value of the mmsIssueProcess property.
     * 
     * @return
     *     possible object is
     *     {@link MmsIssueProcessType }
     *     
     */
    public MmsIssueProcessType getMmsIssueProcess() {
        return mmsIssueProcess;
    }

    /**
     * Sets the value of the mmsIssueProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link MmsIssueProcessType }
     *     
     */
    public void setMmsIssueProcess(MmsIssueProcessType value) {
        this.mmsIssueProcess = value;
    }

    /**
     * Gets the value of the mmsConfigGerneral property.
     * 
     * @return
     *     possible object is
     *     {@link MmsConfigGeneral }
     *     
     */
    public MmsConfigGeneral getMmsConfigGerneral() {
        return mmsConfigGerneral;
    }

    /**
     * Sets the value of the mmsConfigGerneral property.
     * 
     * @param value
     *     allowed object is
     *     {@link MmsConfigGeneral }
     *     
     */
    public void setMmsConfigGerneral(MmsConfigGeneral value) {
        this.mmsConfigGerneral = value;
    }

}
