//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.15 at 12:30:17 PM IST 
//


package mms.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MmsIssueProcessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MmsIssueProcessType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="issueMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastIssuePatientStaffInDays" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastIssueEmployeeInDays" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="onlineIssueDetailsInDays" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="autoReturnRequest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="staffSalePrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="staffSalePriceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="normalSalePrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="normalSalePriceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="strDemandActivePrd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="strDemandActiveFlg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="strWithOutCrNoFlg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="strCrNoDefault" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="strReturnDrugValidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="strDoseFrqFlg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MmsIssueProcessType", propOrder = {
    "issueMode",
    "lastIssuePatientStaffInDays",
    "lastIssueEmployeeInDays",
    "onlineIssueDetailsInDays",
    "autoReturnRequest",
    "staffSalePrice",
    "staffSalePriceType",
    "normalSalePrice",
    "normalSalePriceType",
    "strDemandActivePrd",
    "strDemandActiveFlg",
    "strWithOutCrNoFlg",
    "strCrNoDefault",
    "strReturnDrugValidity",
    "strDoseFrqFlg"
})
public class MmsIssueProcessType {

    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String issueMode;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String lastIssuePatientStaffInDays;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String lastIssueEmployeeInDays;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String onlineIssueDetailsInDays;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String autoReturnRequest;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String staffSalePrice;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String staffSalePriceType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String normalSalePrice;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String normalSalePriceType;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String strDemandActivePrd;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String strDemandActiveFlg;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String strWithOutCrNoFlg;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String strCrNoDefault;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String strReturnDrugValidity;
    @XmlElement(namespace = "http://www.cdacnoida.in/his/MmsConfig", required = true)
    protected String strDoseFrqFlg;

    /**
     * Gets the value of the issueMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueMode() {
        return issueMode;
    }

    /**
     * Sets the value of the issueMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueMode(String value) {
        this.issueMode = value;
    }

    /**
     * Gets the value of the lastIssuePatientStaffInDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastIssuePatientStaffInDays() {
        return lastIssuePatientStaffInDays;
    }

    /**
     * Sets the value of the lastIssuePatientStaffInDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastIssuePatientStaffInDays(String value) {
        this.lastIssuePatientStaffInDays = value;
    }

    /**
     * Gets the value of the lastIssueEmployeeInDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastIssueEmployeeInDays() {
        return lastIssueEmployeeInDays;
    }

    /**
     * Sets the value of the lastIssueEmployeeInDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastIssueEmployeeInDays(String value) {
        this.lastIssueEmployeeInDays = value;
    }

    /**
     * Gets the value of the onlineIssueDetailsInDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnlineIssueDetailsInDays() {
        return onlineIssueDetailsInDays;
    }

    /**
     * Sets the value of the onlineIssueDetailsInDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnlineIssueDetailsInDays(String value) {
        this.onlineIssueDetailsInDays = value;
    }

    /**
     * Gets the value of the autoReturnRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoReturnRequest() {
        return autoReturnRequest;
    }

    /**
     * Sets the value of the autoReturnRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoReturnRequest(String value) {
        this.autoReturnRequest = value;
    }

    /**
     * Gets the value of the staffSalePrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaffSalePrice() {
        return staffSalePrice;
    }

    /**
     * Sets the value of the staffSalePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaffSalePrice(String value) {
        this.staffSalePrice = value;
    }

    /**
     * Gets the value of the staffSalePriceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaffSalePriceType() {
        return staffSalePriceType;
    }

    /**
     * Sets the value of the staffSalePriceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaffSalePriceType(String value) {
        this.staffSalePriceType = value;
    }

    /**
     * Gets the value of the normalSalePrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalSalePrice() {
        return normalSalePrice;
    }

    /**
     * Sets the value of the normalSalePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalSalePrice(String value) {
        this.normalSalePrice = value;
    }

    /**
     * Gets the value of the normalSalePriceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalSalePriceType() {
        return normalSalePriceType;
    }

    /**
     * Sets the value of the normalSalePriceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalSalePriceType(String value) {
        this.normalSalePriceType = value;
    }

    /**
     * Gets the value of the strDemandActivePrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDemandActivePrd() {
        return strDemandActivePrd;
    }

    /**
     * Sets the value of the strDemandActivePrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDemandActivePrd(String value) {
        this.strDemandActivePrd = value;
    }

    /**
     * Gets the value of the strDemandActiveFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDemandActiveFlg() {
        return strDemandActiveFlg;
    }

    /**
     * Sets the value of the strDemandActiveFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDemandActiveFlg(String value) {
        this.strDemandActiveFlg = value;
    }

    /**
     * Gets the value of the strWithOutCrNoFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrWithOutCrNoFlg() {
        return strWithOutCrNoFlg;
    }

    /**
     * Sets the value of the strWithOutCrNoFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrWithOutCrNoFlg(String value) {
        this.strWithOutCrNoFlg = value;
    }

    /**
     * Gets the value of the strCrNoDefault property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCrNoDefault() {
        return strCrNoDefault;
    }

    /**
     * Sets the value of the strCrNoDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCrNoDefault(String value) {
        this.strCrNoDefault = value;
    }

    /**
     * Gets the value of the strReturnDrugValidity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrReturnDrugValidity() {
        return strReturnDrugValidity;
    }

    /**
     * Sets the value of the strReturnDrugValidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrReturnDrugValidity(String value) {
        this.strReturnDrugValidity = value;
    }

    /**
     * Gets the value of the strDoseFrqFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDoseFrqFlg() {
        return strDoseFrqFlg;
    }

    /**
     * Sets the value of the strDoseFrqFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDoseFrqFlg(String value) {
        this.strDoseFrqFlg = value;
    }

}
