//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.05 at 02:41:57 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cdacnoida.in/his/MmsConfig")
package mms.setup;
