package opd.icdsearchengine;

import opd.OpdConfig;

public interface ICDSearchEngineConfig 
{
	String YES = "1";
	String NO = "0";
	
	// Configurable Options
	String ICD_ENGINE_MAIN_DIESEASE_TYPE_SHOW = YES;
	String ICD_ENGINE_AUTO_COMPLETE_INDEX_TERM_SHOW = YES;
	
	// Lucene Index Repository Paths
		// Changed By Pragya dated 2016.07.19 as per requirement in generic path Fetch
	//String LUCENE_PATH_DISEASE_LIST_FOR_WINDOWS="C:/Telangana/AHIMSG5/ICDSearchEngine/icd_repo/";
	//String LUCENE_PATH_DISEASE_LIST_FOR_LINUX="/root/Telangana/AHIMSG5/ICDSearchEngine/icd_repo/";
	String LUCENE_PATH_DISEASE_LIST="/ICDSearchEngine/icd_repo/";

	String LUCENE_INDEX_NAME_DISEASE_LIST="ICDDiseaseList";

	
	//	Search Options
	String[] ICD_ENGINE_SEARCH_OPTION_ARR = {"All", "Volume 1 Tabular List Search", "Volume 3 Alphabetical Index Search", "Reports"};
	String ICD_ENGINE_SEARCH_OPTION_VOLUME_BOTH = "0";
	String ICD_ENGINE_SEARCH_OPTION_VOLUME_1 = "1";
	String ICD_ENGINE_SEARCH_OPTION_VOLUME_3 = "2";
	String ICD_ENGINE_SEARCH_OPTION_TABULAR_LIST = "3";
	
	String ICD_ENGINE_SEARCH_OPTION_DEFAULT = ICD_ENGINE_SEARCH_OPTION_VOLUME_1;
	
	// Order By
	String[] ORDER_BY_ARR = {"Disease Name", "ICD Code"};
	String ORDER_BY_DISEASE_NAME = "0";
	String ORDER_BY_ICD_CODE = "1";
	
	// Disease Master Record Type
	String[] ICD_DISEASE_RECORD_TYPE_ARR = OpdConfig.ICD_DISEASE_RECORD_TYPE_ARR;
	String ICD_DISEASE_RECORD_TYPE_ALL = "-1";
	String ICD_DISEASE_RECORD_TYPE_DISEASE = OpdConfig.ICD_DISEASE_RECORD_TYPE_DISEASE;
	String ICD_DISEASE_RECORD_TYPE_INCLUDE = OpdConfig.ICD_DISEASE_RECORD_TYPE_INCLUDE;
	String ICD_DISEASE_RECORD_TYPE_SYNONYM = OpdConfig.ICD_DISEASE_RECORD_TYPE_SYNONYM;
	
	
	// Search Type
	String ICD_ENGINE_SEARCH_TYPE_NOT_KNOWN = "0";
	String ICD_ENGINE_SEARCH_TYPE_DISEASE_NAME = "1";
	String ICD_ENGINE_SEARCH_TYPE_ICD_CODE = "2";
	String ICD_ENGINE_SEARCH_TYPE_EXACT_ICD_CODE = "3";

	// Keys
	String ICD_ENGINE_LIST_CHRONIC_DISEASES = "icdEngineListChronicDiseases";
	String ICD_ENGINE_LIST_MAIN_DISEASE_TYPES = "icdEngineListMainDiseaseTypes";
	String ICD_ENGINE_LIST_DISEASE_TYPES = "icdEngineListDiseaseTypes";
	String ICD_ENGINE_RESULT_ICD_DISEASE_LIST = "icdEngineResultIcdDiseaseList";
	String ICD_ENGINE_DETAIL_ICD_DISEASE_VO_VIEW_LIST = "icdEngineDetailIcdDiseaseVOViewList";
	String ICD_ENGINE_RESULT_INDEX_TERM_LIST = "icdEngineResultIndexTermList";
	String ICD_ENGINE_LIST_ICD_GROUPS = "icdEngineListICDGroups";
	String ICD_ENGINE_LIST_ICD_SUB_GROUPS = "icdEngineListICDSubGroups";
	String ICD_ENGINE_LIST_ICD_MAIN_DISEASES = "icdEngineListICDMainDiseases";
	
	
	
	
	// Procedure Names
	String PROCEDURE_GET_LIST_ALL_CHRONIC_DISEASES = "PKG_ICD_ENGINE.GET_ALL_CHRONIC_DISEASES";
	String PROCEDURE_GET_LIST_ALL_MAIN_DISEASE_TYPES = "PKG_ICD_ENGINE.GET_ALL_MAIN_DISEASE_TYPES";
	String PROCEDURE_GET_LIST_ALL_DISEASE_TYPES = "PKG_ICD_ENGINE.GET_ALL_DISEASE_TYPES";
	String PROCEDURE_GET_LIST_ALL_ICD_GROUPS = "PKG_ICD_ENGINE.GET_ALL_ICD_GROUPS";
	String PROCEDURE_GET_LIST_ALL_ICD_SUB_GROUPS = "PKG_ICD_ENGINE.GET_ALL_ICD_SUB_GROUPS";
	String PROCEDURE_GET_LIST_ALL_ICD_DISEASES = "PKG_ICD_ENGINE.GET_ALL_ICD_DISEASES";
	String PROCEDURE_GET_RESULT_DISEASE_LIST = "PKG_ICD_ENGINE.GET_RESULT_DISEASE_LIST";
	String PROCEDURE_GET_RESULT_SUB_DISEASE_LIST = "PKG_ICD_ENGINE.GET_RESULT_SUB_DISEASE_LIST";
	String PROCEDURE_GET_DETAIL_ICD_DISEASE_VO = "PKG_ICD_ENGINE.GET_ICD_DISEASE_DTL";
	String PROCEDURE_GET_RESULT_INDEX_LIST = "PKG_ICD_ENGINE.GET_RESULT_INDEX_LIST";
	String PROCEDURE_GET_LIST_ALL_INDEX_TERMS = "PKG_ICD_ENGINE.GET_ALL_INDEX_TERMS";
	String PROCEDURE_GET_SUB_TREE_LIST = "PKG_ICD_ENGINE.GET_SUB_TREE_LIST";
	String PROCEDURE_GET_SUB_SUB_TREE_LIST = "PKG_ICD_ENGINE.GET_SUB_SUB_TREE_LIST";
		//Lucene
	String PROCEDURE_GET_LUCENE_RESULT_DISEASE_LIST = "PKG_ICD_ENGINE.GET_LUCENE_RESULT_DISEASE_LIST";
		
	
	
}