//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.15 at 10:11:21 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cdacnoida.in/his/IpdConfig")
package ipd.setup;
